name: Create Plugin Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract plugin version from acme-bot.php
        id: get_version
        run: |
          VERSION=$(grep -i "Version:" acme-bot.php | head -n 1 | sed 's/.*Version:[[:space:]]*//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: tag_check
        run: |
          TAG="v${{ steps.get_version.outputs.version }}"
          if git ls-remote --tags origin | grep -q "refs/tags/$TAG$"; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Set release tag
        id: set_tag
        run: |
          if [[ "${{ steps.tag_check.outputs.exists }}" == "true" ]]; then
            TAG="v${{ steps.get_version.outputs.version }}-dev.$(date +%Y%m%d%H%M)"
          else
            TAG="v${{ steps.get_version.outputs.version }}"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set_tag.outputs.tag }}
          name: Release ${{ steps.set_tag.outputs.tag }}
          body: |
            Automatically created from master.
            - Commit: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
